//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiLand.Utility4.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HiLand.Utility4.Resource.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 /*!
        /// * Note: While Microsoft is not the author of this file, Microsoft is
        /// * offering you a license subject to the terms of the Microsoft Software
        /// * License Terms for Microsoft ASP.NET Model View Controller 3.
        /// * Microsoft reserves all other rights. The notices below are provided
        /// * for informational purposes only and are not the license terms under
        /// * which Microsoft distributed this file.
        /// *
        /// * jQuery JavaScript Library v1.4.4
        /// * http://jquery.com/
        /// *
        /// * Copyright 2010, John Resig
        /// *
        /// * Incl [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string jquery_1_4_4_min {
            get {
                return ResourceManager.GetString("jquery_1_4_4_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /* For the details, see: http://flowplayer.org/tools/dateinput/index.html#skinning */
        ///
        ////* the input field */
        ///.date {
        ///	border:1px solid #ccc;
        ///	font-size:18px;
        ///	padding:4px;
        ///	text-align:center;
        ///	width:194px;
        ///	
        ///	-moz-box-shadow:0 0 10px #eee inset;
        ///	-webkit-box-shadow:0 0 10px #eee inset;
        ///}
        ///
        ////* calendar root element */
        ///#calroot {
        ///	/* place on top of other elements. set a higher value if nessessary */
        ///	z-index:10000;
        ///	
        ///	margin-top:-1px;
        ///	width:198px;
        ///	padding:2px;
        ///	background-color:#fff;
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string jQuery_tools_dateinput {
            get {
                return ResourceManager.GetString("jQuery_tools_dateinput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /*
        /// * jQuery Tools 1.2.5 - The missing UI library for the Web
        /// * 
        /// * [tabs, tabs.slideshow, tooltip, tooltip.slide, tooltip.dynamic, scrollable, scrollable.autoscroll, scrollable.navigator, overlay, overlay.apple, dateinput, rangeinput, validator, toolbox.flashembed, toolbox.history, toolbox.expose, toolbox.mousewheel]
        /// * 
        /// * NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.
        /// * 
        /// * http://flowplayer.org/tools/
        /// * 
        /// * jquery.event.wheel.js - rev 1 
        /// * Copyright (c) 2008, Three Dub Media (http://threedub [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string jQuery_tools_min {
            get {
                return ResourceManager.GetString("jQuery_tools_min", resourceCulture);
            }
        }
    }
}
