//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiLand.Utility4.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HiLand.Utility4.Resource.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Note: While Microsoft is not the author of this file, Microsoft is
        /// * offering you a license subject to the terms of the Microsoft Software
        /// * License Terms for Microsoft ASP.NET Model View Controller 3.
        /// * Microsoft reserves all other rights. The notices below are provided
        /// * for informational purposes only and are not the license terms under
        /// * which Microsoft distributed this file.
        /// *
        /// * jQuery JavaScript Library v1.4.4
        /// * http://jquery.com/
        /// *
        /// * Copyright 2010, John Resig
        /// *
        /// * Incl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_1_4_4_min {
            get {
                return ResourceManager.GetString("jquery_1_4_4_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* For the details, see: http://flowplayer.org/tools/dateinput/index.html#skinning */
        ///
        ////* the input field */
        ///.date {
        ///	border:1px solid #ccc;
        ///	font-size:18px;
        ///	padding:4px;
        ///	text-align:center;
        ///	width:194px;
        ///	
        ///	-moz-box-shadow:0 0 10px #eee inset;
        ///	-webkit-box-shadow:0 0 10px #eee inset;
        ///}
        ///
        ////* calendar root element */
        ///#calroot {
        ///	/* place on top of other elements. set a higher value if nessessary */
        ///	z-index:10000;
        ///	
        ///	margin-top:-1px;
        ///	width:198px;
        ///	padding:2px;
        ///	background-color:#fff;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jQuery_tools_dateinput {
            get {
                return ResourceManager.GetString("jQuery_tools_dateinput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * jQuery Tools 1.2.5 - The missing UI library for the Web
        /// * 
        /// * [tabs, tabs.slideshow, tooltip, tooltip.slide, tooltip.dynamic, scrollable, scrollable.autoscroll, scrollable.navigator, overlay, overlay.apple, dateinput, rangeinput, validator, toolbox.flashembed, toolbox.history, toolbox.expose, toolbox.mousewheel]
        /// * 
        /// * NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.
        /// * 
        /// * http://flowplayer.org/tools/
        /// * 
        /// * jquery.event.wheel.js - rev 1 
        /// * Copyright (c) 2008, Three Dub Media (http://threedubmedia.com) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jQuery_tools_min {
            get {
                return ResourceManager.GetString("jQuery_tools_min", resourceCulture);
            }
        }
    }
}
